<?php

/**
 * BaseBoard2User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $board_id
 * @property integer $user_id
 * @property Board $Board
 * @property sfGuardUser $User
 * 
 * @method integer     getBoardId()  Returns the current record's "board_id" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method Board       getBoard()    Returns the current record's "Board" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method Board2User  setBoardId()  Sets the current record's "board_id" value
 * @method Board2User  setUserId()   Sets the current record's "user_id" value
 * @method Board2User  setBoard()    Sets the current record's "Board" value
 * @method Board2User  setUser()     Sets the current record's "User" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBoard2User extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('board2_user');
        $this->hasColumn('board_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Board', array(
             'local' => 'board_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}