<?php

/**
 * BaseTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $board_id
 * @property integer $executer_id
 * @property integer $responsible_id
 * @property string $name
 * @property string $description
 * @property date $deadline
 * @property enum $priority
 * @property string $punishment
 * @property enum $status
 * @property string $comment
 * @property boolean $is_failed
 * @property string $punishment_comment
 * @property boolean $is_deadline_changed
 * @property boolean $is_deadline_notification_sent
 * @property Board $Board
 * @property sfGuardUser $Executer
 * @property sfGuardUser $Responsible
 * 
 * @method integer     getBoardId()                       Returns the current record's "board_id" value
 * @method integer     getExecuterId()                    Returns the current record's "executer_id" value
 * @method integer     getResponsibleId()                 Returns the current record's "responsible_id" value
 * @method string      getName()                          Returns the current record's "name" value
 * @method string      getDescription()                   Returns the current record's "description" value
 * @method date        getDeadline()                      Returns the current record's "deadline" value
 * @method enum        getPriority()                      Returns the current record's "priority" value
 * @method string      getPunishment()                    Returns the current record's "punishment" value
 * @method enum        getStatus()                        Returns the current record's "status" value
 * @method string      getComment()                       Returns the current record's "comment" value
 * @method boolean     getIsFailed()                      Returns the current record's "is_failed" value
 * @method string      getPunishmentComment()             Returns the current record's "punishment_comment" value
 * @method boolean     getIsDeadlineChanged()             Returns the current record's "is_deadline_changed" value
 * @method boolean     getIsDeadlineNotificationSent()    Returns the current record's "is_deadline_notification_sent" value
 * @method Board       getBoard()                         Returns the current record's "Board" value
 * @method sfGuardUser getExecuter()                      Returns the current record's "Executer" value
 * @method sfGuardUser getResponsible()                   Returns the current record's "Responsible" value
 * @method Task        setBoardId()                       Sets the current record's "board_id" value
 * @method Task        setExecuterId()                    Sets the current record's "executer_id" value
 * @method Task        setResponsibleId()                 Sets the current record's "responsible_id" value
 * @method Task        setName()                          Sets the current record's "name" value
 * @method Task        setDescription()                   Sets the current record's "description" value
 * @method Task        setDeadline()                      Sets the current record's "deadline" value
 * @method Task        setPriority()                      Sets the current record's "priority" value
 * @method Task        setPunishment()                    Sets the current record's "punishment" value
 * @method Task        setStatus()                        Sets the current record's "status" value
 * @method Task        setComment()                       Sets the current record's "comment" value
 * @method Task        setIsFailed()                      Sets the current record's "is_failed" value
 * @method Task        setPunishmentComment()             Sets the current record's "punishment_comment" value
 * @method Task        setIsDeadlineChanged()             Sets the current record's "is_deadline_changed" value
 * @method Task        setIsDeadlineNotificationSent()    Sets the current record's "is_deadline_notification_sent" value
 * @method Task        setBoard()                         Sets the current record's "Board" value
 * @method Task        setExecuter()                      Sets the current record's "Executer" value
 * @method Task        setResponsible()                   Sets the current record's "Responsible" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task');
        $this->hasColumn('board_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('executer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('responsible_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('deadline', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('priority', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'low',
              1 => 'medium',
              2 => 'high',
             ),
             'default' => 'medium',
             ));
        $this->hasColumn('punishment', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'in_progress',
              1 => 'done',
              2 => 'failed',
              3 => 'archived',
             ),
             'default' => 'in_progress',
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('is_failed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('punishment_comment', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('is_deadline_changed', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_deadline_notification_sent', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Board', array(
             'local' => 'board_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Executer', array(
             'local' => 'executer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Responsible', array(
             'local' => 'responsible_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $user0 = new Doctrine_Template_User(array(
             'cookie' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($user0);
    }
}