<?php

/**
 * Board2UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Board2UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Board2UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Board2User');
    }
}