<?php

/**
 * BoardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Board');
    }
}