<?php

/**
 * PunishmentPresetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PunishmentPresetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PunishmentPresetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PunishmentPreset');
    }
}