<?php

/**
 * Created by PhpStorm.
 * User: alexradyuk
 * Date: 9/18/19
 * Time: 17:35
 */
class TaskFormFinish extends TaskForm
{

    public function configure()
    {

        parent::configure(); // TODO: Change the autogenerated stub

        $this->useFields(['comment']);

        $this->widgetSchema->setFormFormatterName('TableMy');

    }

    public function updateObject($values = null)
    {
        $object = parent::updateObject($values); // TODO: Change the autogenerated stub

        $object->setStatus('done');

        return $object;
    }


    public function doSave($con = null)
    {
        parent::doSave($con); // TODO: Change the autogenerated stub

        //notification
        MyNotificator::notify($this->getObject(), 'finished');
    }


}