<?php

/**
 * Created by PhpStorm.
 * User: alexradyuk
 * Date: 10/2/19
 * Time: 17:36
 */
class TaskFormPunishment extends TaskForm
{

    public function configure()
    {

        parent::configure(); // TODO: Change the autogenerated stub

        $this->useFields(['punishment_comment']);

        $this->validatorSchema['punishment_comment']->setOption('required', true)
            ->setMessage('required', 'Заполните поле');

        $this->widgetSchema->setFormFormatterName('TableMy');

    }

    public function updateObject($values = null)
    {
        $object = parent::updateObject($values); // TODO: Change the autogenerated stub

        $object->setStatus('archived');

        return $object;
    }


    public function doSave($con = null)
    {
        parent::doSave($con); // TODO: Change the autogenerated stub

        //notification
        MyNotificator::notify($this->getObject(), 'punishment_complete');
    }

}