Board:
  columns:
    name: string(255)
  relations:
    Users: {class: sfGuardUser, refClass: Board2User, foreignAlias: Boards, foreign: user_id}

Board2User:
  columns:
    board_id: {type: integer, primary: true, notnull: true}
    user_id: {type: integer, primary: true, notnull: true}
  relations:
    Board: {onDelete: CASCADE}
    User: {class: sfGuardUser, local: user_id, onDelete: CASCADE}

DefaultImage:
  connection: doctrine  
  actAs: [ImageBuilder]
  columns:
    name: string(255)
    title: string(255)
    image: {type: string(255), notnull: true} 

Task:
  actAs:
    Timestampable: ~
    User:
      cookie: false
  columns:
    board_id: {type: integer, notnull: true}
    executer_id: {type: integer, notnull: true}
    responsible_id: {type: integer, notnull: true}
    name: string(255)
    description: string()
    deadline: date
    priority: {type: enum, values: [low, medium, high], default: medium}
    punishment: string()
    status: {type: enum, values: [in_progress, done, failed, archived], default: in_progress}
    comment: string()
    is_failed: {type: boolean, default: false}
    punishment_comment: string()
    is_deadline_changed: boolean
    is_deadline_notification_sent: boolean
  relations:
    Board: {foreignAlias: Tasks, onDelete: CASCADE}
    Executer: {class: sfGuardUser, local: executer_id, foreignAlias: ExecuterTasks, onDelete: CASCADE}
    Responsible: {class: sfGuardUser, local: responsible_id, foreignAlias: ResponsibleTasks, onDelete: CASCADE}

PunishmentPreset:
  columns:
    name: {type: string(255), notnull: true}


Config:
  connection: doctrine
  columns:
    name: {type: string(255), notnull: true}
    title: string(255)
    value: string()
    help: string()
    display: {type: enum, values: [user, system]}
    section: {type: enum, values: [settings, dictionary, system, wiki], default: settings}
    type: {type: enum, values: [integer, float, boolean, text, enum], default: text}
    type_enum_values: string()
    use_wysiwyg: {type: boolean, default: false}
    is_localized: {type: boolean, default: false}

    
TextBlock:
  connection: doctrine
  actAs:
    I18n:
      fields: [text]
  columns:
    name: {type: string(255), notnull: true}
    title: {type: string(255)}
    text: string()
    application: string(32)
    module: string(32)
    special_mark: string(32)
    is_visible_for_admin: {type: boolean, default: false}
  indexes:
    section_index:
      fields: [application, module]







  



